---
# This file is the starting point of the upgrade role. It will do some common prechecks
# required by both eSDS and AFA clusters and find out the node type from the given cluster,
# then it will run the upgrade task for either eSDS or AFA based on the node type.

# Set them to track nodes that succeed/fail during upgrade
- name: Ensure we prepare some global variables
  set_fact:
    sf_node_ids: []
    sf_upgraded: []
    sf_already_upgraded: []
    sf_node_id_name_map: {}
    sf_installed_pkg_ver: "unknown"
    sf_new_pkg_ver: "unknown"
    sf_final_status: "unknown"
    sf_blocking_faults: []
  run_once: True

- name: Ensure we check prerequisites on controller
  include_tasks: precheck-controller.yml

- name: Ensure we check required variables
  include_tasks: precheck-variables.yml

- name: Ensure we know the node type in the cluster
  include_tasks: node-info.yml

- include_tasks: sds-precheck-variables.yml
  when: node_type == "SFc100"

- include_tasks: afa-precheck-variables.yml
  when: node_type != "SFc100"

- name: Ensure we do some pre-upgrade checks on the cluster
  include_tasks: precheck-cluster.yml

- include_tasks: sds-upgrade.yml
  when: node_type == "SFc100" and sf_final_status != "success"

- include_tasks: afa-upgrade.yml
  when: node_type != "SFc100" and sf_final_status != "success"

- name: Post-upgrade
  run_once: True
  delegate_to: localhost
  block:
    - name: Ensure we do some post-upgrade checks on the cluster
      include_tasks: postcheck-cluster.yml

    - name: Ensure we print some stats before exit
      debug:
        msg: "nodes upgraded previously: {{ sf_already_upgraded }}, nodes upgraded in this session: {{ sf_upgraded }}"
      failed_when: sf_final_status != "success"
