---
- name: Ensure we have the Node info
  run_once: True
  delegate_to: localhost
  block:
    - name: "Query node info for cluster {{ sf_mgmt_virt_ip }}"
      include_tasks: cluster-api.yml
      vars:
        http_method: "GET"
        url_cmd: "method=ListAllNodes"

    - set_fact:
       cluster_info: "{{ clus_api_response }}"
      no_log: True

    - name: Ensure we fail if the API call did not return a valid result
      fail:
        msg: "Failed to get node info. {{ cluster_info }}"
      when: >
        cluster_info.json is undefined or
        cluster_info.json.result is undefined or
        cluster_info.json.result.nodes is undefined

    - name: "Save node info for cluster {{ sf_mgmt_virt_ip }}"
      set_fact:
        sf_node_ids: "{{ cluster_info.json.result.nodes | sf_get_node_ids }}"
        sf_cluster_node_data: "{{ cluster_info.json.result.nodes }}"
        node_type: "{{ cluster_info.json.result.nodes[0].platformInfo.nodeType }}"

    - set_fact:
        sf_node_id_name_map: "{{ sf_node_id_name_map|combine({item.nodeID: item.name}) }}"
      with_items: "{{ sf_cluster_node_data }}"
      when: sf_node_id_name_map|length < sf_node_ids|length
      no_log: True
