---
- name: Ensure we have required tools installed
  any_errors_fatal: True
  delegate_to: localhost
  run_once: True
  block:
    - name: Ensure the controller has the required python libraries
      pip:
        name: ['netaddr>=0.7.20', 'dnspython>=2.0.0']
        state: present
        extra_args: "{{ sf_pip_extra_args }}"

    - name: Load ansible version check task
      include_role:
        name: nar_solidfire_sds_compliance
        tasks_from: check_ansible_version.yml
