---
# This will only be called if the node was able to enter Maintenance Mode
# successfully
- name: "Ensure we switch to SolidFire eSDS v{{ sf_new_pkg_ver }} on {{ target_name }}/{{ target_MIP }}"
  when: sf_in_maintenance_mode|bool
  include_role:
    name: nar_solidfire_sds_install
    tasks_from: start-solidfire.yml
  vars:
    desired_state: restarted
